// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhfeuvwypgkbashzffsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoZmV1dnd5cGdrYmFzaHpmZnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjAxOTYsImV4cCI6MjA3MzYzNjE5Nn0.nOiq2LQp1FEPSy6ECN6Ht45Z2Odg5jHqL8AnoCl97eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});